[project]
name = "e-commers"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.10",
]
