# Generated by Django 5.2.7 on 2025-10-28 12:25

import apps.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.managers.UserManager()),
            ],
        ),
    ]
